@startuml
enum ApplicationStatus {
    NewApplication,
    AwaitRegistrationPayment,
    Registration,
    AwaitFirstExpertisePayment,
    AwaitFirstExpertise,
    FirstExpertise,
    AwaitSecondExpertisePayment,
    AwaitSecondExpertise,
    SecondExpertise,
    Approved,
    Rejected,
}
@enduml
